// Generated by scripts/generate_ui_contracts.py; do not edit manually.



export interface AttentionSnapshot {
  generated_at: string;
  horizon_days: number;
  items?: Array<AttentionItem>;
  counts: Record<string, unknown>;
}

export interface AttentionAction {
  kind: string;
  item_id?: string | unknown;
  source?: string | unknown;
  evidence_index?: number | unknown;
}

export interface AttentionEvidence {
  source_type: string;
  title: string;
  url?: string | unknown;
  relative_path?: string | unknown;
  page_numbers?: Array<number>;
  note?: string | unknown;
}

export interface AttentionItem {
  attention_id: string;
  fingerprint: string;
  course_id?: string | unknown;
  course_code?: string | unknown;
  course_title?: string | unknown;
  information_item_id?: string | unknown;
  title: string;
  severity: string;
  reason_codes: Array<string>;
  due_at?: string | unknown;
  date_status?: string | unknown;
  missing_fields?: Array<string>;
  conflicting_sources?: Array<string>;
  affected_source?: string | unknown;
  evidence?: Array<AttentionEvidence>;
  actions?: Array<AttentionAction>;
}

export interface MaterialSearchResult {
  query: string;
  course_ids?: Array<string>;
  indexed_document_count: number;
  indexed_chunk_count: number;
  skipped_document_count: number;
  hits?: Array<MaterialHit>;
}

export interface MaterialHit {
  score: number;
  course_id: string;
  course_title: string;
  activity_id: string;
  activity_name: string;
  source_kind?: string;
  filename: string;
  relative_text_path: string;
  page_start?: number | unknown;
  page_end?: number | unknown;
  source_unit_label?: string | unknown;
  source_unit_start?: number | unknown;
  source_unit_end?: number | unknown;
  chunk_index: number;
  text: string;
  content_tables?: Array<Record<string, unknown>>;
}
