"""Stable use-case port shared by the MCP and UI modules."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


class HIQSPortError(RuntimeError):
    """Safe error that delivery adapters may return to a user or agent."""


@runtime_checkable
class HIQSPort(Protocol):
    """Expose HIQS use cases without leaking storage or collector adapters."""

    @property
    def resources_dir(self) -> Path: ...

    def information_snapshot(self) -> dict[str, Any]: ...

    def application_update_status(self) -> dict[str, object]: ...

    def apply_application_update(self, payload: dict[str, Any]) -> dict[str, object]: ...

    def calendar_ics(self) -> bytes: ...

    def add_course(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def delete_course(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def delete_courses(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def verify_moodle_session(self) -> dict[str, Any]: ...

    def process_ocr_queue(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def apply_personal_inbox(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def material_file(self, relative_path: str) -> tuple[Path, str]: ...

    def source_preview(
        self,
        relative_path: str,
        page_numbers: list[int] | None = None,
    ) -> dict[str, Any]: ...

    def login_moodle(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_courses(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def start_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def retry_failed_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def course_sync_status(self) -> dict[str, Any]: ...

    def cancel_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def login_class_planner(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_class_planner(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def login_sis_course_info(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_sis_course_info(self, payload: dict[str, Any]) -> dict[str, Any]: ...
