"""Stable use-case port shared by the MCP and UI modules."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


class HIQSPortError(RuntimeError):
    """Safe error that delivery adapters may return to a user or agent."""


@runtime_checkable
class InformationQueryPort(Protocol):
    """Read validated information, materials, evidence and calendar projections."""

    @property
    def resources_dir(self) -> Path: ...

    def information_snapshot(self) -> dict[str, Any]: ...

    def status_snapshot(self) -> dict[str, Any]: ...

    def attention_snapshot(self, horizon_days: int = 14) -> dict[str, Any]: ...

    def calendar_ics(self) -> bytes: ...

    def materials_manifest(self, course_ids: list[str] | None = None) -> dict[str, Any]: ...

    def search_materials(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def get_evidence(self, evidence_id: str) -> dict[str, Any]: ...

    def get_evidence_content(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def query_course(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def material_file(self, relative_path: str) -> tuple[Path, str]: ...

    def source_preview(
        self,
        relative_path: str,
        page_numbers: list[int] | None = None,
    ) -> dict[str, Any]: ...

    def moodle_page_preview(self, payload: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class InformationCommandPort(Protocol):
    """Validate and apply explicitly confirmed canonical information changes."""

    def information_update_schema(self) -> dict[str, Any]: ...

    def validate_information_update(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def apply_information_update(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def add_course(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def delete_course(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def delete_courses(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def add_calendar_event(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def delete_calendar_event(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def process_ocr_queue(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def apply_personal_inbox(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def personal_inbox_snapshot(self) -> dict[str, Any]: ...

    def add_personal_inbox(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def add_attention_draft(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def personal_inbox_entry(self, entry_id: str) -> dict[str, Any]: ...

    def pending_changes(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def acknowledge_changes(self, payload: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class CourseSyncPort(Protocol):
    """Authenticate and synchronize authorized HKU course sources."""

    def verify_moodle_session(self) -> dict[str, Any]: ...

    def login_moodle(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_courses(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def start_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def retry_failed_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def course_sync_status(self) -> dict[str, Any]: ...

    def cancel_course_sync(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def login_class_planner(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_class_planner(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def login_sis_course_info(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_sis_course_info(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def synchronize_sis_enrollment(self, payload: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class ApplicationLifecyclePort(Protocol):
    """Expose the pinned, local-application update lifecycle."""

    def application_update_status(self) -> dict[str, object]: ...

    def apply_application_update(self, payload: dict[str, Any]) -> dict[str, object]: ...


@runtime_checkable
class HIQSPort(
    InformationQueryPort,
    InformationCommandPort,
    CourseSyncPort,
    ApplicationLifecyclePort,
    Protocol,
):
    """Aggregate stable capabilities for delivery adapters and composition."""
