"""Small dependency-free JSON Schema to TypeScript generator.

The generated file is intentionally boring and deterministic so it can be
checked into the UI without adding a runtime dependency.
"""

from __future__ import annotations

import json
from typing import Any


def schema_to_typescript(schema: dict[str, Any], root_name: str = "InformationUpdate") -> str:
    definitions = schema.get("$defs", {})
    lines = ["// Generated by `hsas information types`; do not edit manually.", ""]

    def ref_name(ref: str) -> str:
        return ref.rsplit("/", 1)[-1]

    def render(value: dict[str, Any], name: str | None = None) -> str:
        if "$ref" in value:
            return ref_name(value["$ref"])
        if "anyOf" in value:
            options = [render(option) for option in value["anyOf"] if option.get("type") != "null"]
            return " | ".join(dict.fromkeys(options)) or "unknown"
        if "oneOf" in value:
            return " | ".join(render(option) for option in value["oneOf"])
        if "enum" in value:
            return " | ".join(json.dumps(item, ensure_ascii=False) for item in value["enum"])
        kind = value.get("type")
        if kind == "object" or "properties" in value:
            return name or "Record<string, unknown>"
        if kind == "array":
            return f"Array<{render(value.get('items', {}))}>"
        return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(kind, "unknown")

    def emit_interface(name: str, value: dict[str, Any]) -> None:
        lines.append(f"export interface {name} {{")
        required = set(value.get("required", []))
        for key, child in value.get("properties", {}).items():
            child_type = render(child)
            if child.get("type") == "object" or "properties" in child:
                child_type = f"{name}_{key}"
            optional = "" if key in required else "?"
            lines.append(f"  {json.dumps(key, ensure_ascii=False)}{optional}: {child_type};")
        lines.append("}")
        lines.append("")
        for key, child in value.get("properties", {}).items():
            if child.get("type") == "object" or "properties" in child:
                emit_interface(f"{name}_{key}", child)

    for name, value in definitions.items():
        if value.get("type") == "object" or "properties" in value:
            emit_interface(name, value)
    root = schema
    if root.get("type") == "object" or "properties" in root:
        emit_interface(root_name, root)
    return "\n".join(lines).rstrip() + "\n"
