"""Generate the small TypeScript contract surface consumed by the UI.

Usage: .venv/bin/python scripts/generate_ui_contracts.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from hsas.application.material_search import MaterialSearchResult
from hsas.domain.information.attention import AttentionSnapshot


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if schema.get("type") == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "object": "Record<string, unknown>",
    }.get(schema.get("type"), "unknown")


def render_model(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, definition in schema.get("properties", {}).items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {ts_type(definition)};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    schemas: list[tuple[str, dict[str, Any]]] = []
    for name, model in (("AttentionSnapshot", AttentionSnapshot), ("MaterialSearchResult", MaterialSearchResult)):
        root = model.model_json_schema()
        schemas.append((name, root))
        for definition_name, definition in root.get("$defs", {}).items():
            schemas.append((definition_name, definition))
    output = ["// Generated by scripts/generate_ui_contracts.py; do not edit manually.", ""]
    output.extend(render_model(name, schema) for name, schema in schemas)
    target = Path(__file__).parents[1] / "ui/src/contracts.ts"
    target.write_text("\n\n".join(output) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
